(require 'package)
(setq package-check-signature nil)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(defun use-package (name &optional callback)
  (unless (package-installed-p name) (package-install))
  (unless (not callback) (funcall callback))
  )

(package-initialize)
(package-refresh-contents)
(use-package 'gnu-elpa-keyring-update)
(use-package 'exec-path-from-shell 'exec-path-from-shell-initialize)
(use-package 'company (lambda () (global-company-mode t)))
(use-package 'vertico (lambda ()
                        (vertico-mode)
                        (setq completion-styles '(substring basic))
                        ))
(use-package 'eldoc-box (lambda ()
                          (add-hook 'eglot-manage-mode-hook #'eldoc-box-hover-mode t)
                          ))

(defun ts-install-grammars()
  (interactive)
  (mapc #'treesit-install-language-grammar (mapcar #'car treesit-language-source-alist)))

(setq treesit-language-source-alist
   '((bash "https://github.com/tree-sitter/tree-sitter-bash")
     (cmake "https://github.com/uyha/tree-sitter-cmake")
     (c "https://github.com/tree-sitter/tree-sitter-c")
     (cpp "https://github.com/tree-sitter/tree-sitter-cpp")
     (css "https://github.com/tree-sitter/tree-sitter-css")
     (elisp "https://github.com/Wilfred/tree-sitter-elisp")
     (go "https://github.com/tree-sitter/tree-sitter-go")
     (html "https://github.com/tree-sitter/tree-sitter-html")
     (javascript "https://github.com/tree-sitter/tree-sitter-javascript" "master" "src")
     (json "https://github.com/tree-sitter/tree-sitter-json")
     (make "https://github.com/alemuller/tree-sitter-make")
     (markdown "https://github.com/ikatyang/tree-sitter-markdown")
     (python "https://github.com/tree-sitter/tree-sitter-python")
     (toml "https://github.com/tree-sitter/tree-sitter-toml")
     (tsx "https://github.com/tree-sitter/tree-sitter-typescript" "master" "tsx/src")
     (typescript "https://github.com/tree-sitter/tree-sitter-typescript" "master" "typescript/src")
     (yaml "https://github.com/ikatyang/tree-sitter-yaml")))


